// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations.CRUD_Porudzbina
{
    [DbContext(typeof(CRUD_PorudzbinaContext))]
    [Migration("20220420204751_initmigPorudz")]
    partial class initmigPorudz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.Poruzbina", b =>
                {
                    b.Property<int>("IdDostave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDostave");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDostave"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<string>("IdKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdKorisnika");

                    b.Property<string>("Proizvods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Proizvods");

                    b.Property<int>("Stanje")
                        .HasColumnType("int")
                        .HasColumnName("StanjeDostave");

                    b.HasKey("IdDostave");

                    b.ToTable("Porudzbina");
                });
#pragma warning restore 612, 618
        }
    }
}
